### ISSUE TITLE
Remove maximum setuptools version once the circular import issue is resolved

### ISSUE THREAD

**Issue by diazona** [diazona/setuptools-pyproject-migration#61]
We should remove the restriction of `setuptools<=60.10.0` that was added in #60, when we can safely do so - that means either there is a fix in setuptools or some other involved package addressing https://github.com/pypa/setuptools/issues/3744, or we find a less onerous workaround (with "less onerous" meaning that it doesn't eliminate so many versions from consideration).

**Comment by diazona** [comment]
Something interesting to note: on commit 28cd049a0c1061641d619c1415c09db88800d314 we had a [workflow run that passed](https://github.com/diazona/setuptools-pyproject-migration/actions/runs/5851597561/attempts/1) and then [another workflow run that failed](https://github.com/diazona/setuptools-pyproject-migration/actions/runs/5851597561/attempts/2) with the setuptools error. I compared the output of `pip freeze` in the `docs` environment between the two and got the following differences (not counting a meaningless difference in the hash of the built wheel for this package itself):

```diff
11c11
< exceptiongroup==1.1.2
---
> exceptiongroup==1.1.3
13c13
< furo==2023.7.26
---
> furo==2023.8.19
47c47
< Sphinx==7.1.2
---
> Sphinx==7.2.2
50,52c50,52
< sphinxcontrib-applehelp==1.0.6
< sphinxcontrib-devhelp==1.0.4
< sphinxcontrib-htmlhelp==2.0.3
---
> sphinxcontrib-applehelp==1.0.7
> sphinxcontrib-devhelp==1.0.5
> sphinxcontrib-htmlhelp==2.0.4
54,55c54,55
< sphinxcontrib-qthelp==1.0.5
< sphinxcontrib-serializinghtml==1.1.7
---
> sphinxcontrib-qthelp==1.0.6
> sphinxcontrib-serializinghtml==1.1.8
59c59
< types-setuptools==68.0.0.3
---
> types-setuptools==68.1.0.0
```

So it looks like something in that list explains the bug. I'm going to look into it, mostly out of curiosity, but also because if we can figure it out, we can probably relax the restriction in our code. (Or maybe even help get a fix made upstream.)

**Comment by diazona** [comment]
I put both lists into `constraints.txt` files, used them to reproduce both environments on my desktop (with Python 3.10), and they _both_ passed :facepalm: so, no luck on that approach, I guess. There must be some environmental factor that differs between my desktop and the GHA runner that's playing a role in this, but it may not be worth the time to figure out.

**Comment by diazona** [comment]
It looks like the setuptools version restriction (commit 3a2243c655b7f552c6669ad9ca3f3c498c910238) also broke the [documentation build on readthedocs](https://readthedocs.org/projects/setuptools-pyproject-migration/builds/), so that's further incentive to fix this.

**Comment by sjlongland** [comment]
Indeed… I was able to reproduce the issue locally on my Gentoo install, so I might have a crack at this if I get a moment this week-end.

That is, if upstream doesn't come up with a fix before then. :-)

**Comment by diazona** [comment]
Oooh nice! Yeah you should definitely go ahead and run with this, since I haven't managed to reproduce it myself. (also on Gentoo) 

I'm curious how you did it, but that's not so important.

**Comment by sjlongland** [comment]
> Oooh nice! Yeah you should definitely go ahead and run with this, since I haven't managed to reproduce it myself. (also on Gentoo) I think it may still be useful to have the fix in place even if something gets merged upstream, in case someone is stuck using a bad combination of package versions.
> 
> I'm also curious how you did it, but that's not so important.

Quite by accident.  I'm using `venv` for a virtual environment… but that said I'm planning to do a system update on this machine (I have my old desktop building `.tbz2` packages right now) so hopefully I don't "break" my test case in the process. :-)

**Comment by diazona** [comment]
In that case can I suggest recording as much info as you can about your environment before doing updates? It might be useful to reproduce this issue in the future if the update changes anything relevant. I mean, given that I've already seen that the error can appear or not appear in different virtual environments with the same listening of packages, there must be some external factor involved and I think more information can only help narrow down what it is.

**Comment by sjlongland** [comment]
What I'll probably try first, will be shifting the work directory over to the machine I just updated, and see if the problem reproduces there.

If it does, then the issue is in the `venv`, not the host environment.

**Comment by sjlongland** [comment]
Yep, can reproduce it even with the latest updates:

```
RC=0 stuartl@beast ~/projects/setuptools-pyproject-migration/work $ tox -e docs
docs: recreate env because python changed virtualenv version='20.23.0'->'20.24.2'
docs: remove tox env folder /home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs
.pkg: recreate env because python changed virtualenv version='20.23.0'->'20.24.2'
.pkg: remove tox env folder /home/stuartl/projects/setuptools-pyproject-migration/work/.tox/.pkg
.pkg: install_requires> python -I -m pip install 'setuptools<=60.10.0; python_version < "3.12"' 'setuptools>=56' 'setuptools_scm[toml]>=3.4.1'
.pkg: _optional_hooks> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: package config for docs is editable, however the build backend setuptools.build_meta does not support PEP-660, falling back to editable-legacy - change your configuration to it
.pkg: get_requires_for_build_wheel> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: install_requires_for_build_wheel> python -I -m pip install wheel
.pkg: prepare_metadata_for_build_wheel> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
docs: install_package_deps> python -I -m pip install furo 'importlib-metadata; python_version < "3.8"' 'jaraco.packaging>=9.3' packaging pep508-parser 'pytest-console-scripts>=1.2' pytest-cov 'pytest-enabler>=2.2; python_version >= "3.8"' 'pytest>=6' 'rst.linker>=1.9' setuptools 'setuptools<=60.10.0; python_version < "3.12"' 'setuptools>=56' 'setuptools_scm[toml]>=3.4.1' sphinx-lint 'sphinx>=3.5' tomlkit types-setuptools 'typing-extensions<5,>=4'
docs: install_package> python -I -m pip install --force-reinstall --no-deps -e /home/stuartl/projects/setuptools-pyproject-migration/work
docs: commands[0] /home/stuartl/projects/setuptools-pyproject-migration/work/docs> python -m sphinx -W --keep-going . /home/stuartl/projects/setuptools-pyproject-migration/work/build/html
Running Sphinx v7.2.3
loading pickled environment... done
/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/build/env.py:201: EncodingWarning: 'encoding' argument not specified
  with tempfile.NamedTemporaryFile('w+', prefix='build-reqs-', suffix='.txt', delete=False) as req_file:
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://setuptools.pypa.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 2 source files that are out of date
updating environment: [config changed ('project')] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] index
generating indices... genindex py-modindex done
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in ../build/html.
docs: commands[1] /home/stuartl/projects/setuptools-pyproject-migration/work/docs> python -m sphinxlint
/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/regex/regex.py:470: EncodingWarning: UTF-8 Mode affects locale.getpreferredencoding(). Consider locale.getencoding() instead.
  pattern_locale = _getpreferredencoding()
No problems found.
.pkg: _exit> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  docs: OK (123.13=setup[101.44]+cmd[21.47,0.22] seconds)
  congratulations :) (123.81 seconds)
RC=0 stuartl@beast ~/projects/setuptools-pyproject-migration/work $ tox -e docs
docs: recreate env because python changed virtualenv version='20.23.0'->'20.24.2'
docs: remove tox env folder /home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs
.pkg: recreate env because python changed virtualenv version='20.23.0'->'20.24.2'
.pkg: remove tox env folder /home/stuartl/projects/setuptools-pyproject-migration/work/.tox/.pkg
.pkg: install_requires> python -I -m pip install 'setuptools>=56' 'setuptools_scm[toml]>=3.4.1'
.pkg: _optional_hooks> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_editable> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: install_requires_for_build_editable> python -I -m pip install wheel
.pkg: build_editable> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
docs: install_package_deps> python -I -m pip install furo 'importlib-metadata; python_version < "3.8"' 'jaraco.packaging>=9.3' packaging pep508-parser 'pytest-console-scripts>=1.2' pytest-cov 'pytest-enabler>=2.2; python_version >= "3.8"' 'pytest>=6' 'rst.linker>=1.9' setuptools sphinx-lint 'sphinx>=3.5' tomlkit types-setuptools 'typing-extensions<5,>=4'
docs: install_package> python -I -m pip install --force-reinstall --no-deps /home/stuartl/projects/setuptools-pyproject-migration/work/.tox/.tmp/package/58/setuptools_pyproject_migration-0.1.dev276+g3c0930c-0.editable-py3-none-any.whl
docs: commands[0] /home/stuartl/projects/setuptools-pyproject-migration/work/docs> python -m sphinx -W --keep-going . /home/stuartl/projects/setuptools-pyproject-migration/work/build/html
Running Sphinx v7.2.3
loading pickled environment... done
/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/build/env.py:201: EncodingWarning: 'encoding' argument not specified
  with tempfile.NamedTemporaryFile('w+', prefix='build-reqs-', suffix='.txt', delete=False) as req_file:
loading intersphinx inventory from https://packaging.pypa.io/en/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://setuptools.pypa.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 2 source files that are out of date
updating environment: [config changed ('project')] 2 added, 0 changed, 0 removed
reading sources... [100%] index
WARNING: autodoc: failed to import module 'setuptools_pyproject_migration'; the following exception was raised:
Traceback (most recent call last):
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 64, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
looking for now-outdated files... none found
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/src/setuptools_pyproject_migration/__init__.py", line 3, in <module>
    import setuptools
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/__init__.py", line 17, in <module>
    from setuptools.dist import Distribution
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/_virtualenv.py", line 90, in exec_module
    old(module)
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/dist.py", line 37, in <module>
    from setuptools.config import setupcfg, pyprojecttoml
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/config/__init__.py", line 8, in <module>
    from . import setupcfg
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 38, in <module>
    from . import expand
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/config/expand.py", line 53, in <module>
    from setuptools.dist import Distribution  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'Distribution' from partially initialized module 'setuptools.dist' (most likely due to a circular import) (/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/dist.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 88, in import_object
    module = import_module(modname, warningiserror=warningiserror)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 68, in import_module
    raise ImportError(exc, traceback.format_exc()) from exc
ImportError: (ImportError("cannot import name 'Distribution' from partially initialized module 'setuptools.dist' (most likely due to a circular import) (/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/dist.py)"), 'Traceback (most recent call last):\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 64, in import_module\n    return importlib.import_module(modname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import\n  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked\n  File "<frozen importlib._bootstrap_external>", line 940, in exec_module\n  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/src/setuptools_pyproject_migration/__init__.py", line 3, in <module>\n    import setuptools\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/__init__.py", line 17, in <module>\n    from setuptools.dist import Distribution\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/_virtualenv.py", line 90, in exec_module\n    old(module)\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/dist.py", line 37, in <module>\n    from setuptools.config import setupcfg, pyprojecttoml\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/config/__init__.py", line 8, in <module>\n    from . import setupcfg\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 38, in <module>\n    from . import expand\n  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/config/expand.py", line 53, in <module>\n    from setuptools.dist import Distribution  # noqa\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nImportError: cannot import name \'Distribution\' from partially initialized module \'setuptools.dist\' (most likely due to a circular import) (/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/dist.py)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 64, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/src/setuptools_pyproject_migration/__init__.py", line 3, in <module>
    import setuptools
  File "/home/stuartl/projects/setuptools-pyproject-migration/work/.tox/docs/lib/python3.11/site-packages/setuptools/__init__.py", line 35, in <module>
    __version__ = setuptools.version.__version__
                  ^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'setuptools' has no attribute 'version' (most likely due to a circular import)

pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] index
generating indices... genindex done
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build finished with problems, 1 warning.
docs: exit 1 (13.91 seconds) /home/stuartl/projects/setuptools-pyproject-migration/work/docs> python -m sphinx -W --keep-going . /home/stuartl/projects/setuptools-pyproject-migration/work/build/html pid=10769
.pkg: _exit> python /home/stuartl/projects/setuptools-pyproject-migration/env/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  docs: FAIL code 1 (47.87=setup[33.96]+cmd[13.91] seconds)
  evaluation failed :( (48.01 seconds)
```
